version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      # Prefix all commit messages with "chore: "
      prefix: 'chore'
    open-pull-requests-limit: 10
